version: '3.8'

services:
  api:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - db
    environment:
      - NODE_ENV=production
    volumes:
      - .:/app
    restart: always

  db:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nest_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: